### ISSUE TITLE
playstate

### ISSUE THREAD

**Issue by moekdegroot** [lucasvdh/codes.lucasvdh.android-tv#1]
Hi Lucas, just installed your app on homey and it works great with an nvidia shield. Just wondering if the playstate could also be implemented. That way I can for instance turn of the lights when playing, turn the lights on in a dimmed state when paused and have lights go to normal lighting when stopped. 

Best, Moek

**Comment by CoonHouse** [comment]
+1
I would also like to see flow-triggers for "play-start" and "pause". You think that would be possible?
Thanks

**Comment by lucasvdh** [comment]
Hi @moekdegroot,

I don't think the Android Remote API provides the option to read the current play state of the connected device. I'll have another look but I'm not sure I'll find anything. This is mostly due to the client being reverse engineered without any official documentation.

Because of this I also don't think the "play/start" and "pause" flow triggers will be possible.

**Comment by moekdegroot** [comment]
Hi Lucas,
Thanks for replying and I'm very sorry for not replying sooner. Don't know why I didn't get a notification but I just stumbled by accident on your message. 
Closing the issue. 
Thanks for getting back to me!
Best, Moek
