### ISSUE TITLE
"Turned On/Off" stopped working for me

### ISSUE THREAD

**Issue by ghost** [lucasvdh/codes.lucasvdh.android-tv#12]
Hi and sorry if this question already has been asked.

Last few weeks the When statement "Turned On" and "Turned Off" does not work as they used to for me. The way I used them was with flows like this:

When I turned my Android TV Off with my physical remote, I also initiated my receiver to also turn off. And "vice versa", using mentioned "When" statements.

Now, the flow is not activated as it was many months before. However, if I "turn off" the box from the Homey device, the flow is activated...even though the box is also immediately turned on again, but that's probably another issue.

I can see that the "app" is listed as a remote, so maybe I am totally off, bit previously it have been able to trigger on state, as described.

Any advice would be helpful. Thanks.

**Comment by lucasvdh** [comment]
Hi Ola,

It sounds like you're encountering issues with the integration between your Android TV and the Homey app.

Given that these flows worked previously but are now experiencing problems, there are a couple of potential causes. It could be due to a problem with the Android remote service, or an issue within the Homey app itself. 

---

Since there haven't been any recent updates that might have directly affected this functionality, here are a few steps you can take to try and resolve the issue:

1. **Restart the Homey App**
    Sometimes, simply restarting the app can resolve minor glitches or communication issues.
2. **Restart yourt Android TV device**
    https://homey-android-tv.gitbook.io/en/overview/faq#why-is-my-device-unavailable
    In many cases, connectivity issues can be attributed to a crashed Remote Service on your Android TV, which is the component that the Homey app communicates with. To resolve this, you can try performing a hard reboot of your Android TV. 
    
    Here's how:
    - **Completely Power Down**: Turn off your Android TV using the remote control or the power button on the TV itself.
    - **Unplug from Power**: Once turned off, unplug your Android TV from the power source. Wait for about 30 seconds to a minute.
    - **Plug Back In**: Reconnect the power cable to your Android TV and power it on.
    - **Check Homey App**: After your Android TV has fully restarted, open the Homey app again and check if the device is now available.
    
    Performing a hard reboot can often resolve issues related to the Remote Service and restore connectivity to the Homey app.

---

Please try these steps and let me know if any of these resolve your issue. Your understanding of the situation and cooperation are much appreciated.

**Comment by ghost** [comment]
Hi Lucas, 
Many thanks for you tips - now it works! I should have thought of the "standard solution" of course :) 

I assume you meant restarting the Homey Pro rather than the app - did both though. Cannot say which of the steps that did it, but I think it was restarting the Android TV box that did it.

**Comment by lucasvdh** [comment]
Good to hear!

Remember to fully shut down your Android TV device occasionally, as not doing so could lead to the Android Remote Service app crashing. A hard reboot usually fixes this problem.
